CREATE TABLE IF NOT EXISTS BOOK
(
  ID INT PRIMARY KEY IDENTITY,
  AUTHOR VARCHAR(100),
  NAME VARCHAR(100),
  TEXT LONGVARCHAR,
  NEW_TEXT LONGVARCHAR,
  STATUS VARCHAR(100),
  DATE TIMESTAMP,
  URL VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS CURRENT_EPISODE
  (
  ID INT PRIMARY KEY IDENTITY,
  NAME VARCHAR(200),
  EPISODE VARCHAR(4),
  DATE TIMESTAMP
  );
